version: 2
sources:
  - name: sana-sandbox-356306
    database: sana-sandbox-356306
    schema: dbt_schand
    tables:
      - name: address
      - name: rate_plan_product
      - name: sms_record
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}